# Generated by Django 2.1.7 on 2019-02-12 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nazwa')),
                ('type', models.IntegerField(choices=[(1, 'Fundacja'), (2, 'Organizacja'), (3, 'Lokalna zbiórka')], verbose_name='Rodzaj')),
                ('mission', models.CharField(max_length=255, verbose_name='Misja')),
                ('location', models.IntegerField(choices=[(1, 'dolnośląskie'), (2, 'lubelskie'), (3, 'łódzkie'), (4, 'mazowieckie'), (5, 'podkarpackie'), (6, 'pomorskie'), (7, 'świętokrzyskie'), (8, 'wielkopolskie'), (9, 'kujawsko-pomorskie'), (10, 'lubuskie'), (11, 'małopolskie'), (12, 'opolskie'), (13, 'podlaskie'), (14, 'śląskie'), (15, 'warmińsko-mazurskie'), (16, 'zachodniopomorskie')], verbose_name='Województwo')),
                ('town', models.CharField(max_length=64, verbose_name='Miejscowość')),
                ('help', models.IntegerField(choices=[(1, 'dzieciom'), (2, 'samotnym matkom'), (3, 'bezdomnym'), (4, 'niepełnosprawnym'), (5, 'osobom starszym'), (6, 'bezrobotnym')], verbose_name='Komu pomaga')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Data urodzenia')),
                ('description', models.CharField(max_length=255, verbose_name='Opis')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d', verbose_name='Zdjęcie profilowe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
        ),
        migrations.AddField(
            model_name='helppackage',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_name', to='main.Organization'),
        ),
    ]
