# Generated by Django 2.1.7 on 2019-02-14 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nazwa')),
                ('type', models.IntegerField(choices=[(1, 'Fundacja'), (2, 'Organizacja'), (3, 'Lokalna zbiórka')], verbose_name='Rodzaj')),
                ('mission', models.CharField(max_length=255, verbose_name='Misja')),
                ('help', models.IntegerField(choices=[(1, 'dzieciom'), (2, 'samotnym matkom'), (3, 'bezdomnym'), (4, 'niepełnosprawnym'), (5, 'osobom starszym'), (6, 'bezrobotnym')], verbose_name='Komu pomaga')),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Towns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nazwa')),
                ('province', models.IntegerField(choices=[(1, 'dolnośląskie'), (2, 'lubelskie'), (3, 'łódzkie'), (4, 'mazowieckie'), (5, 'podkarpackie'), (6, 'pomorskie'), (7, 'świętokrzyskie'), (8, 'wielkopolskie'), (9, 'kujawsko-pomorskie'), (10, 'lubuskie'), (11, 'małopolskie'), (12, 'opolskie'), (13, 'podlaskie'), (14, 'śląskie'), (15, 'warmińsko-mazurskie'), (16, 'zachodniopomorskie')], verbose_name='Województwo')),
            ],
        ),
        migrations.RemoveField(
            model_name='helppackage',
            name='organization',
        ),
        migrations.AddField(
            model_name='helppackage',
            name='bags',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='helppackage',
            name='books',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='helppackage',
            name='city',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='helppackage',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='helppackage',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='helppackage',
            name='others',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='helppackage',
            name='phone_num',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='helppackage',
            name='post_code',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='helppackage',
            name='street',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='helppackage',
            name='toys',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='helppackage',
            name='usable_clothes',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='helppackage',
            name='useless_clothes',
            field=models.BooleanField(null=True),
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.AddField(
            model_name='institution',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='main.Towns'),
        ),
        migrations.AddField(
            model_name='helppackage',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_name', to='main.Institution'),
        ),
    ]
