# Generated by Django 2.1.7 on 2019-02-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_helppackage_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helppackage',
            options={'verbose_name_plural': 'Utworzone dary'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name_plural': 'Zaufane instytucje'},
        ),
        migrations.AlterModelOptions(
            name='towns',
            options={'verbose_name_plural': 'Miasta'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'Profile użytkowników'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_num',
            field=models.CharField(default='brak', max_length=20, verbose_name='Telefon'),
            preserve_default=False,
        ),
    ]
